### ISSUE TITLE
[FEATURE]: Support for running reconcile against targets on Databricks that reside in hive_metastore or AWS glue based catalogs

### ISSUE THREAD

**Issue by ajalisatgi** [databrickslabs/remorph#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of feature request

Reconcile

### Problem statement

Remorph currently does not support running reconciliation against Databricks targets that are currently in non-UC based catalogs such as the default `hive_metastore` or `AWS Glue` based catalogs.   

### Proposed Solution

Enable support for running reconciliation against `hive_metastore` or `AWS Glue` based catalogs so that it can be adopted by customers who have not completely onboarded to UC.

**Comment by nfx** [comment]
Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this request. All of our features assume UC-only workspaces, so that we ensure the best-in-class support for data governance, which is not possible with other metastore protocols.
